### ISSUE TITLE
Shows clipboard as selected text when nothing is selected

### ISSUE THREAD

**Issue by charleshan** [aabuhijleh/electron-selected-text#1]
`getSelectedText()` shows clipboard as selected text when nothing is selected.

**Comment by aabuhijleh** [comment]
@charleshan which OS are you having this problem on?

The existing clipboard content should be cleared by [this](https://github.com/aabuhijleh/electron-selected-text/blob/master/src/index.ts#L10) then a keyboard copy (cmd/ctrl+c) event is synthesized and the selection is read form the clipboard (after a 200ms delay to make sure the clipboard has the selection).

**Comment by charleshan** [comment]
Oh you're right. The problem was how VS Code handles the clipboard. It acts as if the current line is selected when nothing is selected for some reason.
